""" Main Snakefile for VISSEQ pipeline
"""
import os

### setup report ###
if os.path.exists('config.yaml'):
    configfile: 'config.yaml'
elif os.path.exists('default-config.yaml'):
    configfile: 'default-config.yaml'
#configfile: "config/config.yaml"

#report: "report/workflow.rst"

### setup config variables ###
include: "rules/config.smk"

### load rules ###
include: "rules/setup.smk"
include: "rules/io.smk"
include: "rules/merging.smk"
include: "rules/alignment.smk"
include: "rules/stitching.smk"
include: "rules/segmentation.smk"
include: "rules/sequencing.smk"
include: "rules/phenotyping.smk"
include: "rules/qc.smk"

### target rules ###



